#!/bin/sh
# скрипт для системи vim documents53

template_dir="${1:-$HOME/.config/nvim/templates/templates53}"
selection="${XDG_RUNTIME_DIR:-/tmp}/doc53-selection"

find "$template_dir" -mindepth 2 -maxdepth 2 -type f -name "*.org" \
| xargs -I {} dirname "{}" \
| sort -u \
| fzf --delimiter="/" --with-nth=-1 > "$selection"
